### ISSUE TITLE
Implement "standard" map/collection methods

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/flurry#10]
This issue tracks the implementation status of various "standard" methods on collections in general and maps in particular that should be added to flurry. Checked boxes have already been "claimed".

 - [ ] [`drain`] (**hard**) and `IntoIterator` (**easy**) for both owned and `&` (see #33)

If you want to pick up any of these, leave a comment here and/or open a draft PR!

  [`drain`]: https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.drain

**Comment by Stupremee** [comment]
I would like to implement Eq, Index and clear.

**Comment by jonhoo** [comment]
@Stupremee How about you do `Eq` and `Index` first, and then we do `clear` in a separate PR afterwards?

**Comment by danielSanchezQ** [comment]
I think I can try to implement the `Clone` one . Is it ok?

**Comment by jonhoo** [comment]
Absolutely, it's all yours!

**Comment by Stupremee** [comment]
I will also implement Debug since Index doesnt work atm

**Comment by danielSanchezQ** [comment]
I think I can do `with_hasher` and `with_capacity_and_hasher` also. But I see them as checked already.

**Comment by jonhoo** [comment]
@danielSanchezQ Those are already (accidentally) being added in #24

**Comment by soruh** [comment]
I'd like to take a crack at implementing `reserve`.

**Comment by jonhoo** [comment]
@soruh all yours!

**Comment by danielSanchezQ** [comment]
I can give a try to the `retain` method 😄

**Comment by soruh** [comment]
I took a quick look at `drain` and `into_iter` in #33, but I'm not sure how correct & efficient what I wrote actually is.

**Comment by soruh** [comment]
@jonhoo I'd appreciate it if you could mark the `drain` and `IntoIter` impls as open (maybe with a link to my existing work); I don't really have the time to look into this further at the moment (I'm still open for questions about my initial implementation #33). I'll write another comment if I have the time to work on this and no one already has.

**Comment by jonhoo** [comment]
I'm replacing this with https://github.com/jonhoo/flurry/issues/62 now that there's just one item left.
