### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by ibraheemdev** [jonhoo/flurry#127]
flurry has been a very interesting concurrent hash table experiment and has driven a lot of innovation in that space. However, at this point, flurry suffers from performance as well as [memory usage](https://github.com/jonhoo/flurry/issues/115) issues under load. These are likely artifacts of the underlying implementation being geared for a garbage collected language and difficult to solve without a design overhaul. [dashmap](https://github.com/xacrimon/dashmap) and [papaya](https://github.com/ibraheemdev/papaya) provide better performance and memory usage across the board. flurry is still a very popular crate, does it make sense to bring attention to some of these issues in the README?

**Comment by jonhoo** [comment]
Yes, I think it does! I don't feel strongly that flurry must be an "equal competitor" in the space, so would happily take a PR that adds a "better alternatives" section to the readme and crate docs.
