### ISSUE TITLE
no_std + alloc

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/flurry#26]
This crate _should_ be possible to write using only [`core`](https://doc.rust-lang.org/core/) and [`alloc`](https://doc.rust-lang.org/alloc/), and thus be usable in `no_std` environments.

The `hashbrown` implementation should be hugely helpful in figuring out how to do this. In particular, see the magical incantations in [`src/lib.rs`](https://github.com/rust-lang/hashbrown/blob/master/src/lib.rs) and the use of `alloc` and `core` in [`src/raw/mod.rs`](https://github.com/rust-lang/hashbrown/blob/master/src/raw/mod.rs). We may be able to simplify some of those since `hashbrown` has to [pull some tricks](https://github.com/rust-lang/hashbrown/blob/6f5826ed934a5e6342681c27618bea71f9b0c800/Cargo.toml#L23-L26) so that it can be pulled into `std`. Compare for example with the `no_std` support in [`crossbeam-epoch/src/lib.rs`](https://github.com/crossbeam-rs/crossbeam/blob/c0a999d2f15935a895cbcee16f3b46746d5174b7/crossbeam-epoch/src/lib.rs#L59).

There are a couple of things that we have to figure out how to operate in a `no_std` environment:
 - `crossbeam-epoch` will need `default-features = false` and `features = ["alloc"]`. This will [remove `epoch::pin`](https://github.com/crossbeam-rs/crossbeam/blob/c0a999d2f15935a895cbcee16f3b46746d5174b7/crossbeam-epoch/src/lib.rs#L104) (but not `epoch::Guard` I think), and we'll need to figure out whether the API is still usable (and maybe include some examples).
 - `RandomState` is only available with `std`, so we will want to add a `std` feature (which is on by default) and only expose it when the feature is enabled. We'll also have to figure out how that affects the [`default value for S`](https://github.com/jonhoo/flurry/blob/2a5bd258fa805e89715f7dbd52b63bddf736490f/src/lib.rs#L262).
 - Neither `num_cpus` nor `Once` (which we use for [`NCPU`](https://github.com/jonhoo/flurry/blob/2a5bd258fa805e89715f7dbd52b63bddf736490f/src/lib.rs#L247)) are available on `no_std`. We'll need to figure out how to [determine the stride](https://github.com/jonhoo/flurry/blob/2a5bd258fa805e89715f7dbd52b63bddf736490f/src/lib.rs#L837) for transfers without it.
 - We currently use `std::thread::yield_now` if we detect an [initialization race](https://github.com/jonhoo/flurry/blob/2a5bd258fa805e89715f7dbd52b63bddf736490f/src/lib.rs#L472-L473). It's not entirely clear what we do in this case in a `no_std` environment. I _think_ it is fine for us to use [`spin_loop_hint`](https://doc.rust-lang.org/core/sync/atomic/fn.spin_loop_hint.html) if the `std` isn't set for the following reason: for there to be a race, there _must_ be another thread running concurrently with us. That thread cannot be blocked on us, since we are not in any mutually-exclusive section. So our goal is just to not waste cycles and give it some time to complete. It is not a _requirement_ that we fully yield.

**Comment by GarkGarcia** [comment]
On regards to your second point, we could revert back to the old strategy in an `no_std` environment.

**Comment by GarkGarcia** [comment]
Started working on this in https://github.com/jonhoo/flurry/pull/44.

**Comment by jonhoo** [comment]
I'm going to close this for the time being, as we have no compelling use-cases, and the implementation ends up complicating the API a fair amount: #48. If someone does see a strong need for this and are willing to take on supporting this, then let me know and I'll re-open!
