### ISSUE TITLE
Implement `HashSet::replace`

### ISSUE THREAD

**Issue by GarkGarcia** [jonhoo/flurry#75]
Std's `HashSet` exposes the [`HashSet::replace`](https://doc.rust-lang.org/std/collections/struct.HashSet.html#method.replace) method, which is useful for situations where `==` potentially returns true even if it's arguments are structurally different. This should be a very trivial to fix.

Also, it should be easy to implement `HashSet::is_subset` and `HashSet::is_superset` equivalents.

**Comment by GarkGarcia** [comment]
I'll work on this and #17 as soon as we're done with #74.

**Comment by GarkGarcia** [comment]
I don't think implementing `HashSet::replace` is viable, since `HashMap::put` always leaves the key unchanged. I guess this should be closed?

**Comment by jonhoo** [comment]
Ah, yes, you're right... That's awkward. I guess the user would have to remove and then re-add. Which we probably want them to do explicitly. In _theory_ we could also make the key an `Atomic`, but that seems like more trouble than it's worth, and a pretty bad perf hit. Let's close this!
