### ISSUE TITLE
Unsoundness in `HashMap::clear`

### ISSUE THREAD

**Issue by ibraheemdev** [jonhoo/flurry#98]
`HashMap::clear` does not have `K\V: Send + Sync` bounds, even though it calls `defer_destroy` on nodes and values, which might call the destructors on another thread. Unless I am missing something, this is unsound and could cause undefined behavior.

**Comment by jonhoo** [comment]
Ah, yes, you are entirely right! Good catch. Would you mind submitting a PR with a fix?
